# Azure Pipeline YAML file

name: 0.6$(Rev:.r)

trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'

variables:
  _IS_BUILD_CI: false
  _RELEASE_NAME: docker-woocommerce
  _RELEASE_VERSION: latest
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'Build and Package $(_RELEASE_NAME)'
  inputs:
    filePath: .ci/build.ps1
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub_ci
- task: Docker@2
  condition: and(eq(variables._IS_BUILD_CI, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: Build and Push (CI)
  inputs:
    containerRegistry: dockerhub_ci
    repository: julianxhokaxhiu/docker-woocommerce
    command: buildAndPush
    tags: latest
- task: Docker@2
  condition: and(eq(variables._IS_BUILD_CI, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: Build and Push (Stable)
  inputs:
    containerRegistry: dockerhub_ci
    repository: julianxhokaxhiu/docker-woocommerce
    command: buildAndPush
    tags: $(_RELEASE_VERSION)
