# Azure Pipeline YAML file

name: 0.6$(Rev:.r)

trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'

variables:
  _TRIVY_VERSION: 0.44.1
  _IS_BUILD_CI: false
  _RELEASE_NAME: julianxhokaxhiu/docker-woocommerce
  _RELEASE_TAG: latest
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Prepare environment'
  inputs:
    filePath: .ci/prepare.sh
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub_ci
- task: Docker@2
  displayName: Build
  inputs:
    repository: $(_RELEASE_NAME)
    command: build
    tags: $(_RELEASE_TAG)
- task: Bash@3
  displayName: 'Run security scan'
  inputs:
    filePath: .ci/scan.sh
- task: Docker@2
  condition: and(eq(variables._IS_BUILD_CI, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: Push (CI)
  inputs:
    containerRegistry: dockerhub_ci
    repository: $(_RELEASE_NAME)
    command: push
    tags: $(_RELEASE_TAG)
- task: Docker@2
  condition: and(eq(variables._IS_BUILD_CI, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: Push (Stable)
  inputs:
    containerRegistry: dockerhub_ci
    repository: $(_RELEASE_NAME)
    command: push
    tags: $(_RELEASE_TAG)
