name: DockerWoocommerce

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
    branches:
    - master

env:
  _RELEASE_NAME: julianxhokaxhiu/docker-woocommerce
  _RELEASE_VERSION: v0
  _BUILD_VERSION: "0.6.${{ github.run_number }}"
  _BUILD_BRANCH: "${{ github.ref }}"

jobs:
  DockerWoocommerce:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
    - name: Prepare environment
      run: ".github/workflows/prepare.ps1"
      shell: pwsh
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: julianxhokaxhiu
        password: "${{ secrets.DOCKERHUB_CI_DOCKER_PASSWORD }}"
    - name: Build
      uses: docker/build-push-action@v5
      with:
        tags: ${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW'
    - name: Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}
